let uploadedFileContent = "";

// Read the uploaded file
document
  .getElementById("fileInput")
  .addEventListener("change", function (event) {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = function (e) {
        uploadedFileContent = e.target.result;
      };
      reader.readAsText(file);
    }
  });

// Patch the plugins and trigger download
document.getElementById("patchButton").addEventListener("click", function () {
  try {
    // Parse the uploaded file content
    const script = document.createElement("script");
    script.textContent = uploadedFileContent;
    document.body.appendChild(script);

    // Patch the plugins data (credit [g f y] - discord: @.go.fuck.yourself.)
    const patchedContent = `// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n${JSON.stringify(
      $plugins
    )
      .replace(/{"name":/g, '\n{"name":')
      .replace(/\]$/, "\n];")}`;

    // Create a Blob with the patched content
    const blob = new Blob([patchedContent], { type: "text/javascript" });
    const url = URL.createObjectURL(blob);

    // Create a temporary anchor element and trigger download
    const a = document.createElement('a');
    a.href = url;
    a.download = 'plugins.js';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error("Error processing file:", error);
    alert("Error patching plugins: " + error.message);
  }
});

// Show the patch button when a file is selected
document.getElementById("fileInput").addEventListener("change", function () {
  const patchDiv = document.getElementById("patch");
  if (this.files.length > 0) {
    patchDiv.style.display = "block";
  } else {
    patchDiv.style.display = "none";
  }
});
